# Generated by Django 5.2.3 on 2025-07-02 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0003_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
